### ISSUE TITLE
Could you restrict access to this repository?

### ISSUE THREAD

**Issue by AndreMiras** [dincamihai/csvapi#2]
Hi Mihai Dincă,
I'm Andre, I work at [Elements](https://www.elements.nl).
I came across your repository which is an implementation of one of our technical test we give for the backend position.
While I truly encourage open source, we prefer it not to have the tests and solutions public because other candidates may use it :confused: 
Do you mind making this repository private or deleting it please? FWIW [BitBucket](https://bitbucket.org) has private repository as part as its free price plan.
Thanks in advance and have a nice day :smiley:

**Comment by dincamihai** [comment]
@AndreMiras thanks for pointing this out. I will delete the repo.
